CREATE TABLE IF NOT EXISTS public.afip_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  establishment_id uuid NOT NULL REFERENCES public.establishments(id) ON DELETE CASCADE,
  service text NOT NULL DEFAULT 'wsfe',
  environment text NOT NULL DEFAULT 'production',
  token text NOT NULL,
  sign text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (establishment_id, service, environment)
);

GRANT ALL ON public.afip_tokens TO service_role;
ALTER TABLE public.afip_tokens ENABLE ROW LEVEL SECURITY;

UPDATE public.afip_certificates
SET certificate_pem = '-----BEGIN CERTIFICATE-----
MIIDQDCCAiigAwIBAgIIB6Te89WSCTwwDQYJKoZIhvcNAQENBQAwMzEVMBMGA1UEAwwMQ29tcHV0
YWRvcmVzMQ0wCwYDVQQKDARBRklQMQswCQYDVQQGEwJBUjAeFw0yNjA4MTQxNTE5MzZaFw0yODA4
MTMxNTE5MzZaMCsxDjAMBgNVBAMMBWRhdHRhMRkwFwYDVQQFExBDVUlUIDI3OTQ3NTI4ODI5MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2GbgGXRizoW17FzMvy1EG8MS5A+B1Q0ni63H
eVOzb99j8GZ96Z3jstocChfgXTy/LeLQG3Pper0CCh6ACPlG/Z7bt467E5JF4RfZ2uEPz7PJ2xdQ
+rIQWE2UCUDzD+dIpyi3u1UScUbuIkIkk5gNkacIa08apbJF9Dy3VqKT8FsIQgw4yuJaaCs3N9kp
Q0lcv0hEO7vgZkSD99fO6X8nidhoChV394Kkox1CGHBXvvo9sD4RKAsyJ8lDhU5kBf7uVpyxPYGl
Ts180KXyZTCKDiIP3AE34dRPsZA9IO/K4QYsk4U6N5zo9JldqH8l8KgJD47e3R9/aBfLLphLKpYc
cQIDAQABo2AwXjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFCsNL8jfYf0IyU4R0DWTBG2OW9Bu
MB0GA1UdDgQWBBQ5RTVBwNNSCtZ/GCRY46Ucx3+XPjAOBgNVHQ8BAf8EBAMCBeAwDQYJKoZIhvcN
AQENBQADggEBALJuwt6rw8zmucLu3KxGOnjvTkjTT6B2K3kqlkXW5KAsE31F1osXupQLXZQYWLzh
Fa9pEjkBLrIxQAQnJk8fIuZ9D3BDY/TxGNfTQ2FelOiPnHVYruKGgb5V8RHEfNDrtw1izdHEqbwe
O2PMrDSIi5bcScuqsIWPfUjLrQ4Lml82CE9m/t6Xg2XH5G/cWfT7HyGhJ4lrPpSV5Qo9bIUSUQu8
eIOjNIrN+qZ4pWfkRQDiUYkbhc0gb7VeQrzHzc1gYfSgsRRHRj2n4BP9dG/qRFRyv55JoFPbnhxU
ueefRsxYdpjWjUNNw4pKzGhdfKSowItUsBeskkp9VkIjfK8w74w=
-----END CERTIFICATE-----',
    expires_at = '2028-08-13'
WHERE establishment_id = '5a56bc2d-c69b-49e7-96b4-7ff690ad8140';